
def S_func(string):
    for i in range(len(string)):
        s = ''
        s += string[i:i+4]
        counter = string.count(s)
        if counter > 3:
            print(f'substring {s} is {counter} times')
    if len(string) >= 4:
        S_func(string[1:])
    
S_func('glypwjzsjgwbuzripawjldyqarkkoamnzurpqmzsiqdijaqfpwyleqrwsslpstkxsjkuplceuwgyzsxfwqirxckozfqqrsipvucelzckkovuawiglmrocwfyhcpvrwpiulsfsvisjrvucxyjrsxdagbwurowlpfvdvpwohrqnjmnkzuopcogwlnijehpxcmlchylcwrwbudbhakagxdipooegyxfafuhfmaagtdxpgjyzqkagnschcwjkqrokvcwbvwgspgkcdxafeqylcelqashbsdycdsexcngfumsklikhbpggsuhfmaagkkkxawbkdvorksrfrsrdsixcmlcvzjrjpaelhxgwnoulyayrsjlxwraourpgmjbvfdmlcqreviqpvvzvelyoelxxsnbshrsmgsulxxmpvvlxxcnbvwewswzcbgmrdhyhkmbktrfkfjaprvsgyhzpwrilswwlswycsehbmajodhpsppvvpkmliskkyhzukylmlyszrqswqahlslyrpvvwovkswwlkwuazcdcxfahvfrrmhcxbsxqazwkkwcrccyohoqwkhkfgpgzqmigpkrvpmpohtrsrczwedlsspoegswlkklvohkkfvebsyzzpskvreqlokvjuppwrieabvukpnqpclmxmisrqkagzsidxkcktnlbijagjfyqkqbzfkxgkbkhmllkzfjsiqswwlewcodvurenohyhwsqpjzvsfjaarqsjcohrwsslktnlpmgohyhmsdbsvvrsnhogwytrqbvgmspzzvvcpwebkrkajwbrqnlcjqvlxxmpvvzyvjzkzgoacxplwcskadyrxisosivwmedhrocszarflxkgpppzsjgrczsfsgysfyovrdszqdipjsksbsrkqfozlmjsjhxezhslvovqpcjsoeipcfwripojzddlcebkhbrcphyhsransrvsrewjrlvezezzwisdswwlwiyjgkkkxnacgooagpvmrstndcehcgyjijhdlciafuoelzafuopggsdrlmjadyrxiqpocnsreswkkpvgabuvkrbyccooeeqsjrfippvvlxxcnbvwpvmihyhcekaqfipicovfssrudwtkdlcuqfqxiaphyhsvjwdkrzwrkhyhgsphrnlniuapnlpmgoijhnmlioebyxfafrszpgyoklyrqwgnhvpqkavwopcrwjlyrqwfvjymlckzisejhcnlxktesnhbwrkkrqnipwpfxdxfawikyyqagnldlrdszuyallciwkfjagtuoilocehmskloebbiaabkoisdbsihneawavukxfwhtrxrcyhjwyxfawewovlahmlkagbwrovsuebxsosnhskroqyezgkyxmohfibmcjrjdxhakzchkksagulbiapzpibskpvvlbgyisidcekkfvperbwbveexuervvzvcwrlvosdswwlswgjqfpwyleq')